name: polaris
services:
    polaris:
        tty: true
        container_name: polaris
        ports:
            - 5050:5050
        volumes:
            - /root/tank/nas/Eigene_Musik:/music
            - ./cache:/var/cache/polaris
            - ./data:/var/lib/polaris
        image: registry.gitlab.com/connectical/container/polaris
        restart: unless-stopped
