services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /media/music:/media
    restart: 'unless-stopped'
    ports:
      - '8096:8096' # Public HTTP Port