version: '3.9'
services:
    mariadb:
        container_name: mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=T0pS€cr€tPässörd
        image: 'mariadb:latest'
    myadmin:
        container_name: myadmin
        links:
            - 'mariadb:db'
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
        image: 'phpmyadmin'
    php:
        image: webdevops/php-nginx-dev:8.2
        working_dir: /app
        environment:
        - WEB_DOCUMENT_ROOT=/app/public
        - PHP_DISPLAY_ERRORS=1
        - PHP_MEMORY_LIMIT=2048M
        - PHP_MAX_EXECUTION_TIME=-1
        - XDEBUG_MODE=debug
        - XDEBUG_START_WITH_REQUEST=yes
        - XDEBUG_CLIENT_PORT=9000
        - XDEBUG_CLIENT_HOST=host.docker.internal
        - XDEBUG_MAX_NESTING_LEVEL=1000
        ports:
        - "88:80"
        volumes:
        - ./:/app:rw,cached
